"""rename address

Revision ID: 96195394fe09
Revises: f37be77c0525
Create Date: 2025-06-10 14:45:23.841405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96195394fe09'
down_revision = 'f37be77c0525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
